%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%    Make a map from a .dat file    %
%                                   %
%    Created By: Daniel Kulas       %
%             10/15/12              %
%                                   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%% Load up .dat map generated by robot%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load robot_map.dat
robotmap = robot_map;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%% The (0,0) is the starting coordinate for the map, and the (120, 120)  %%%%%%%%
%%%%%%%% value is the max location/size of map. Create a rectangle in place    %%%%%%%% 
%%%%%%%%         of where the map specifies an obstacle                        %%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


rectangle('Position',[0,0,120,120]) % 8m x 8m
val = 0;

free_val = 0;
obstacle_val = 0;

for i = 1:1:120
    for j = 1:1:120
        val = robotmap(i,j);
        if val >= 1
            rectangle('Position',[i-1,j-1, 1, 1]);
        end
    end
end


